# Copyright (c) Datalayer, Inc. https://datalayer.io
# Distributed under the terms of the MIT License.

name: datalayer-examples
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
    - datalayer-run
    - jupyter_server==2.10
    - jupyter_client==8.6.0
    - jupyterlab==4.1.0b0
#    - jupyter-resource-usage==1.0.1
