# Copyright (c) 2025-2026 Datalayer, Inc.
#
# BSD 3-Clause License

"""Put a project's pyproject.toml and uv.lock in an Environment spec (PLAN_ENV.md E3-08).

    make pyproject.yaml
    python pyproject_spec.py pyproject > pyproject.yaml
    python pyproject_spec.py ../../../../research/data-analysis --name agentic-data-analysis \
        --title "Agentic data analysis" \
        --check "import pandas, duckdb; print(pandas.__version__, duckdb.__version__)" \
        > data-analysis.yaml

A `pyproject` source carries both files inline, the way a `requirements`
source carries its file: the lock is checked and exported before anything is
queued. A real uv.lock runs to hundreds of kilobytes, which is why the example
keeps them as files and writes the spec from them.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

SPEC = """\
# Generated by pyproject_spec.py from {folder}/pyproject.toml and {folder}/uv.lock.
apiVersion: environments.datalayer.io/v1alpha1
kind: Environment
metadata:
  name: {name}
  title: {title}
spec:
  language:
    name: python
    version: "3.13"
  base:
    ref: datalayer/python-cpu
    channel: "2026.09"
  compatibility:
    variants:
      required: [datalayer]
      optional: [daytona]
  build:
    source: dependencyFile
    dependencyFile:
      sourceFormat: pyproject
      content: |
{content}
      lockContent: |
{lock}
  commands:
    postInstall:
      - python -c "{check}"
"""


def _block(text: str) -> str:
    """The file as a YAML literal block, eight spaces in."""
    return "\n".join(("        " + line).rstrip() for line in text.splitlines())


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("folder", nargs="?", default="pyproject")
    parser.add_argument("--name", default="pyproject-example")
    parser.add_argument("--title", default="From a pyproject.toml and its uv.lock")
    parser.add_argument(
        "--check",
        default="import pyfiglet, jupyter_server; print(pyfiglet.__version__, jupyter_server.__version__)",
        help="The Python the build runs after installing the lock, as its postInstall.",
    )
    arguments = parser.parse_args()
    root = Path(arguments.folder)
    lock = root / "uv.lock"
    if not lock.exists():
        sys.exit(f"No {lock}: run `uv lock` in {arguments.folder} first")
    sys.stdout.write(
        SPEC.format(
            folder=arguments.folder,
            name=arguments.name,
            title=arguments.title,
            check=arguments.check.replace('"', '\\"'),
            content=_block((root / "pyproject.toml").read_text(encoding="utf-8")),
            lock=_block(lock.read_text(encoding="utf-8")),
        )
    )


if __name__ == "__main__":
    main()
