# Copyright (c) 2025-2026 Datalayer, Inc.
#
# BSD 3-Clause License

"""Put a project's pyproject.toml and uv.lock in an Environment spec (PLAN_ENV.md E3-08).

    make pyproject.yaml
    python pyproject_spec.py pyproject > pyproject.yaml

A `pyproject` source carries both files inline, the way a `requirements`
source carries its file: the lock is checked and exported before anything is
queued. A real uv.lock runs to hundreds of kilobytes, which is why the example
keeps them as files and writes the spec from them.
"""

from __future__ import annotations

import sys
from pathlib import Path

SPEC = """\
# Generated by pyproject_spec.py from {folder}/pyproject.toml and {folder}/uv.lock.
apiVersion: environments.datalayer.io/v1alpha1
kind: Environment
metadata:
  name: pyproject-example
  title: From a pyproject.toml and its uv.lock
spec:
  language:
    name: python
    version: "3.13"
  base:
    ref: datalayer/python-cpu
    channel: "2026.09"
  compatibility:
    variants:
      required: [datalayer]
      optional: [daytona]
  build:
    source: dependencyFile
    dependencyFile:
      sourceFormat: pyproject
      content: |
{content}
      lockContent: |
{lock}
  commands:
    postInstall:
      - python -c "import pyfiglet, jupyter_server; print(pyfiglet.__version__, jupyter_server.__version__)"
"""


def _block(text: str) -> str:
    """The file as a YAML literal block, eight spaces in."""
    return "\n".join(("        " + line).rstrip() for line in text.splitlines())


def main(folder: str) -> None:
    root = Path(folder)
    lock = root / "uv.lock"
    if not lock.exists():
        sys.exit(f"No {lock}: run `uv lock` in {folder} first")
    sys.stdout.write(
        SPEC.format(
            folder=folder,
            content=_block((root / "pyproject.toml").read_text(encoding="utf-8")),
            lock=_block(lock.read_text(encoding="utf-8")),
        )
    )


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "pyproject")
